language: node_js
node_js:
  - "9"
install:
  - cd ..
  - mkdir hyoo
  - mv offer.hyoo.ru hyoo/offer
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start hyoo/offer
  - rm hyoo/offer/.gitignore
  - mv hyoo/offer/- offer.hyoo.ru
  - mv hyoo/offer/CNAME offer.hyoo.ru/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
