name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build app
      uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'hyoo/offer'
    
    - name: Deploy on GitHub Pages
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.0.1
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: 'hyoo/offer/-'
